version: '3'
services:
  nodejsapp:
    build: .
    image: afzaalahmadzeeshan/express-nodejs:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: ".1"
          memory: 100M
      restart_policy: 
        condition: on-failure
    ports:
      - "1234:5000"
    networks:
      - appnetwork

networks:
  appnetwork: